#!/usr/bin/env python3
"""Verification cell for the Lipschitz-spine primitive: build a hollow duct and measure its genus.

What it does: drive lipschitz_spine_v1.hollow_duct_from_spine() with the synthetic room generated by
synthetic_room_v1.py (a rectangular room with two internal wall segments leaving a doorway, and a
floor route straight through that doorway), then measure the built mesh's genus with the canonical
topology instrument genus_v1.py.

WHAT GETS BUILT -- this is what needs genus 1, not the solid rod the raw primitive alone gives: a
plain union-of-balls tube is a SOLID, topologically a ball, genus 0; a DUCT is a SHELL with the lumen
open at both ends, topologically a napkin ring, genus 1, exactly the reference body class in
genus_v1.py's own _facit_kroppar(), "N through holes in a block":
  1. INNER lumen: the primitive over the room's clearance grid, with the wall+safety margin applied,
     so the primitive itself does the shrink (independently re-derived from the raw grid, NOT read
     off the room's own reference R array -- see the cross-check below).
  2. The lumen EXTENDED past both mouths (straight along the end tangents) so the subtraction punches
     all the way through the outer wall's rounded end caps -- otherwise the "hole" is a blind cavity
     (n_hallrum, not a handle; that is genus_v1.py's own tunnel1_hallrum1 counterexample, used here
     on purpose as the discriminant, see FALLBEVIS_BLIND_HALA below).
  3. OUTER wall: the SAME primitive call with radii = r_used+WALL and an unconstrained hazard field,
     so it degenerates to a plain union-of-balls chain -- one code path, not a second tube builder.
  4. tree = subtract(outer, inner_extended) (expr.py's existing op, k=0 hard).

The cell's own verdict gate: handles_summa == 1, n_hallrum == 0, the mesh watertight, the blind-lumen
discriminant PASS, the extreme-radius condition holding per station, and a lossless JSON round-trip.

Run: python lipschitz_spine_v1_verify.py
Output: artifacts/ikarus_lipschitz_v1.json
"""
from __future__ import annotations

import json
import os
import sys
import time

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import expr as E                      # noqa: E402
import eval_warp as W                 # noqa: E402
import genus_v1 as G                  # noqa: E402
import lipschitz_spine_v1             # noqa: E402
import synthetic_room_v1              # noqa: E402
from lipschitz_spine_v1 import lipschitz_spine_tube  # noqa: E402

ART = os.path.join(HERE, "artifacts")
AST = os.path.join(ART, "synthetic_room_v1")
OUTP = os.path.join(ART, "ikarus_lipschitz_v1.json")
WALL, SAFETY = 2.5, 1.0
DEVICE = os.environ.get("FIELD_ENGINE_DEVICE") or W.DEVICE
R_AMBITIOUS = 12.0     # deliberately larger than the room's own reference R at the doorway, so the
                       # primitive's OWN clamp does the work rather than passing a safe caller value
PITCHES_MC = (0.8, 0.45)
T0 = time.time()


def log(m):
    print(f"[verify] {time.time()-T0:7.1f}s {m}", flush=True)


def mesh_via_ikarus(tree, bbox_lo, bbox_hi, pitch, device):
    """Marching-cubes a compiled IKARUS tree -- the same pattern as proofs.py's facet_scaling_proof
    (eval_warp.eval_batch -> skimage.measure.marching_cubes)."""
    from skimage import measure
    lo = np.asarray(bbox_lo) - 2 * pitch
    hi = np.asarray(bbox_hi) + 2 * pitch
    ns = np.ceil((hi - lo) / pitch).astype(int) + 1
    xs = lo[0] + pitch * np.arange(ns[0])
    ys = lo[1] + pitch * np.arange(ns[1])
    zs = lo[2] + pitch * np.arange(ns[2])
    X, Y, Z = np.meshgrid(xs, ys, zs, indexing="ij")
    pts = np.stack([X.ravel(), Y.ravel(), Z.ravel()], axis=1)
    vals = W.eval_batch(tree, pts, device=device).reshape(ns[0], ns[1], ns[2])
    if not (vals.min() < 0.0 < vals.max()):
        raise RuntimeError(f"level-0 not bracketed: min={vals.min():.3f} max={vals.max():.3f}")
    verts, faces, _n, _v = measure.marching_cubes(vals, level=0.0, spacing=(pitch, pitch, pitch))
    verts = verts + lo[None, :]
    return verts, faces


def main():
    if not os.path.exists(os.path.join(AST, "spine_v1.npz")):
        synthetic_room_v1.write(AST)
    A = np.load(os.path.join(AST, "spine_v1.npz"), allow_pickle=False)
    C, R_ref, T_tan = A["C"], A["R"], A["T"]
    Fld = np.load(os.path.join(AST, "falt_rum.npz"), allow_pickle=False)
    d_free, origin, pitch_grid = Fld["d_free"], Fld["origin"], float(Fld["pitch"])
    n = len(C)
    log(f"synthetic room spine n={n} bbox={C.min(0).round(1)}..{C.max(0).round(1)} "
        f"R_ref=[{R_ref.min():.2f},{R_ref.max():.2f}]")

    res = {"cell": "ikarus_lipschitz_v1",
           "input": "synthetic_room_v1 (declared room, generated clearance field and floor route)"}

    # ---------------------------------------------------------------- (1) INNER lumen via the
    # primitive, re-derived from the RAW clearance grid (not from the room's own reference R).
    r_ambitious = np.full(n, R_AMBITIOUS)
    duct_tree, outer_tree, inner_tree, audit = lipschitz_spine_v1.hollow_duct_from_spine(
        C, r_ambitious, d_free, origin, pitch_grid, wall_mm=WALL, safety_mm=SAFETY,
        tangents_mm=T_tan, r_min_mm=1.0, mouth_margin_mm=5.0)
    r_used = np.array(audit["r_used_mm"])
    res["MOUTH_STUB"] = audit["mouth_stub"]
    res["TREE"] = {"node_count": E.node_count(duct_tree), "leaf_ops": sorted(E.leaf_ops(duct_tree))}
    res["INNER_LUMEN_SHRINK"] = {
        "n_stations": n, "n_shrunk": audit["n_shrunk"], "n_dropped": audit["n_dropped_below_r_min"],
        "r_desired_mm": R_AMBITIOUS, "r_used_min_mm": round(float(r_used.min()), 3),
        "r_used_median_mm": round(float(np.median(r_used)), 3),
        "r_used_max_mm": round(float(r_used.max()), 3),
        "min_margin_slack_mm": audit["min_margin_slack_mm"]}
    log(f"inner lumen shrunk {audit['n_shrunk']}/{n}, r_used=[{r_used.min():.2f},{r_used.max():.2f}]")

    # CROSS-CHECK against the room's OWN reference R (an independent path: theirs is smoothed and
    # R_MAX-clipped, ours is raw and unsmoothed off the SAME grid -- they should be close but not
    # bit-identical; report the actual deviation, do not assert a tautology).
    dev = r_used - R_ref
    # TOLERANCE, derived not picked: the reference profile smooths with a 7-station box filter and
    # separately clips with min() against the unsmoothed solution, so the two arrays can legitimately
    # disagree by up to about the largest single-segment dR/ds change times the filter half-width
    # (3 stations).
    max_dR_adjacent = float(np.abs(np.diff(R_ref)).max())
    tol_mm = max_dR_adjacent * 3.0
    res["CROSS_CHECK_VS_REFERENCE_R"] = {
        "metod": "my r_used (the primitive's OWN clamp on the RAW grid) against the room generator's "
                 "R (same condition, but smoothed with a 7-station box filter and R_MAX-clipped). "
                 "The difference must be small and dominated by the smoothing, not by a different "
                 "formula.",
        "mean_abs_dev_mm": round(float(np.abs(dev).mean()), 4),
        "max_abs_dev_mm": round(float(np.abs(dev).max()), 4),
        "max_adjacent_dR_reference_mm": round(max_dR_adjacent, 4),
        "tol_mm_derived_from_filter_window": round(tol_mm, 4),
        "mine_within_derived_smoothing_tolerance": bool(np.abs(dev).max() < tol_mm)}
    log(f"cross-check vs reference R: mean|dev|={np.abs(dev).mean():.4f}mm "
        f"max={np.abs(dev).max():.4f}mm tol={tol_mm:.2f}mm")

    device = DEVICE
    log(f"device={device}; meshing the duct via eval_batch + marching cubes at TWO resolutions "
        f"(convergence check: a genus that changes with tessellation is a measurement error)")
    _ms = audit["mouth_stub"]
    stub_reach = _ms["spacing_mm"] * max(_ms["n_ext_mouth0"], _ms["n_ext_mouth1"]) + 3.0
    bbox_lo = C.min(0) - (r_used.max() + WALL + stub_reach)
    bbox_hi = C.max(0) + (r_used.max() + WALL + stub_reach)

    res["PITCH_CONVERGENCE"] = {"rader": []}
    topo_fine = None
    pitch_mc = PITCHES_MC[0]
    for pitch_mc in PITCHES_MC:
        t0 = time.time()
        verts, faces = mesh_via_ikarus(duct_tree, bbox_lo, bbox_hi, pitch_mc, device)
        topo_i = G.mesh_topologi(verts, faces)
        topo_i.pop("_svetsad", None)
        row = {"pitch_mm": pitch_mc, "n_verts": len(verts), "n_faces": len(faces),
               "handles_summa": topo_i["handles_summa"], "n_hallrum": topo_i["n_hallrum"],
               "n_randkomponenter": topo_i["n_randkomponenter"],
               "vattentat_mesh": topo_i["vattentat_mesh"], "sekunder": round(time.time() - t0, 1)}
        res["PITCH_CONVERGENCE"]["rader"].append(row)
        log(f"  pitch={pitch_mc}mm: {len(verts)}v {len(faces)}f handles={topo_i['handles_summa']} "
            f"n_hallrum={topo_i['n_hallrum']} n_comp={topo_i['n_randkomponenter']} "
            f"({row['sekunder']}s)")
        topo_fine = topo_i   # keep the finest resolution's result as the reported measurement
    rows = res["PITCH_CONVERGENCE"]["rader"]
    res["PITCH_CONVERGENCE"]["konvergerat"] = bool(
        rows[-1]["handles_summa"] == rows[-2]["handles_summa"]
        and rows[-1]["n_hallrum"] == rows[-2]["n_hallrum"]) if len(rows) >= 2 else False
    topo = topo_fine

    res["GENUS_MEASURED"] = {
        "instrument": "genus_v1.py mesh_topologi",
        "pitch_mm": rows[-1]["pitch_mm"],
        "handles_summa": topo["handles_summa"], "n_hallrum": topo["n_hallrum"],
        "n_randkomponenter": topo["n_randkomponenter"], "vattentat_mesh": topo["vattentat_mesh"],
        "heltaligt": topo["heltaligt"], "n_kanter_ej_delade_av_2": topo["n_kanter_ej_delade_av_2"],
        "meshvolym_mm3": topo["meshvolym_mm3"]}
    log(f"GENUS (finest, pitch={rows[-1]['pitch_mm']}mm): handles_summa={topo['handles_summa']} "
        f"n_hallrum={topo['n_hallrum']} n_randkomponenter={topo['n_randkomponenter']} "
        f"watertight={topo['vattentat_mesh']} converged={res['PITCH_CONVERGENCE']['konvergerat']}")

    # ---------------------------------------------------------------- falsification #1 (breaks the
    # condition): an extreme desired radius fed straight in WITHOUT the primitive would create a
    # material pillar; verify the primitive instead shrinks every station and never emits an
    # oversized ball.
    extreme_tree, extreme_audit = lipschitz_spine_tube(C, 60.0, d_free, origin, pitch_grid,
                                                      wall_mm=WALL, safety_mm=SAFETY, r_min_mm=1.0)
    r_extreme = np.array(extreme_audit["r_used_mm"])
    res["FALLBEVIS_EXTREM_RADIE"] = {
        "r_desired_mm": 60.0, "n_shrunk": extreme_audit["n_shrunk"], "n_stations": n,
        "alla_krympta": bool(extreme_audit["n_shrunk"]
                             >= n - extreme_audit["n_dropped_below_r_min"]),
        "r_used_max_mm": round(float(r_extreme.max()), 3),
        "villkor_haller_for_varje_station": bool(extreme_audit["min_margin_slack_mm"] is None
                                                 or extreme_audit["min_margin_slack_mm"] >= -1e-6),
        "konstruktorn_krymper_avvisar_inte": bool(extreme_audit["n_live"] > 0)}
    log(f"falsification, extreme r=60: n_shrunk={extreme_audit['n_shrunk']}/{n} "
        f"r_used_max={r_extreme.max():.2f} min_margin_slack={extreme_audit['min_margin_slack_mm']}")

    # ---------------------------------------------------------------- falsification #2 (the
    # discriminant): a BLIND lumen (not extended past the outer caps) must NOT give genus 1 -- it
    # must fall into the tunnel1_hallrum1 counterexample class genus_v1.py's own reference warns
    # about (handles=0, n_hallrum>=1). If capping the lumen still read genus 1, the measurement chain
    # itself would be broken, not just the primitive.
    blind_tree = E.subtract(outer_tree, inner_tree)   # the UN-extended inner built above, step 1
    verts2, faces2 = mesh_via_ikarus(blind_tree, bbox_lo, bbox_hi, pitch_mc, device)
    topo2 = G.mesh_topologi(verts2, faces2)
    topo2.pop("_svetsad", None)
    res["FALLBEVIS_BLIND_HALA_DISKRIMINANT"] = {
        "syfte": "if the lumen is NOT extended past the outer shell's ends the result is a BLIND "
                 "cavity: handles_summa MUST be 0 and n_hallrum MUST be >= 1 (the same counterexample "
                 "as genus_v1.py's tunnel1_hallrum1) -- otherwise the measurement chain is measuring "
                 "the wrong quantity.",
        "handles_summa": topo2["handles_summa"], "n_hallrum": topo2["n_hallrum"],
        "n_randkomponenter": topo2["n_randkomponenter"],
        "diskriminant_PASS": bool(topo2["handles_summa"] == 0.0 and topo2["n_hallrum"] >= 1)}
    log(f"falsification, blind lumen: handles={topo2['handles_summa']} "
        f"n_hallrum={topo2['n_hallrum']} "
        f"(diskriminant_PASS={res['FALLBEVIS_BLIND_HALA_DISKRIMINANT']['diskriminant_PASS']})")

    # ---------------------------------------------------------------- JSON round-trip of the node
    # composition (plain expr.py dicts -- expr.save/load round-trips it losslessly with no new
    # (de)serialisation code, which is the whole point of composing instead of adding a wp.func).
    p1 = os.path.join(ART, "ikarus_lipschitz_v1_tree.json")
    E.save(duct_tree, p1)
    reloaded = E.load(p1)
    js_a, js_b = json.dumps(duct_tree, sort_keys=True), json.dumps(reloaded, sort_keys=True)
    p_test = tuple(C[0])
    v_before = E.eval_sdf_py(duct_tree, p_test) if "gridfield" not in E.leaf_ops(duct_tree) else None
    v_after = E.eval_sdf_py(reloaded, p_test) if "gridfield" not in E.leaf_ops(reloaded) else None
    res["ROUND_TRIP"] = {"artifact": os.path.relpath(p1, HERE),
                         "json_identical": bool(js_a == js_b),
                         "eval_sdf_py_before": v_before, "eval_sdf_py_after": v_after,
                         "eval_identical": bool(v_before == v_after)}
    log(f"round-trip: json_identical={res['ROUND_TRIP']['json_identical']} "
        f"eval_identical={res['ROUND_TRIP']['eval_identical']}")

    # ---------------------------------------------------------------- composition-is-free proof:
    # the duct tree compiles through the SAME compile_expr/eval_batch path as any other expr tree.
    before_cache = len(W._KERNEL_CACHE)
    _ = W.eval_batch(extreme_tree, C[:3], device=device)
    after_cache = len(W._KERNEL_CACHE)
    res["GPU_COMPOSITION_FREE"] = {
        "metod": "extreme_tree is evaluated through the SAME eval_warp.eval_batch()/compile_expr() "
                 "as every other tree -- no new wp.func was written for this node type.",
        "kernel_cache_entries_before": before_cache, "kernel_cache_entries_after": after_cache,
        "ny_kernel_kompilerad": bool(after_cache > before_cache),
        "eval_warp_py_modifierad": False, "expr_py_modifierad": False}
    log(f"composition free: kernel cache {before_cache}->{after_cache}")

    res["VERDICT"] = "PASS" if (
        res["GENUS_MEASURED"]["handles_summa"] == 1.0
        and res["GENUS_MEASURED"]["n_hallrum"] == 0
        and res["GENUS_MEASURED"]["vattentat_mesh"]
        and res["PITCH_CONVERGENCE"]["konvergerat"]
        and res["FALLBEVIS_BLIND_HALA_DISKRIMINANT"]["diskriminant_PASS"]
        and res["FALLBEVIS_EXTREM_RADIE"]["villkor_haller_for_varje_station"]
        and res["ROUND_TRIP"]["json_identical"]
        and not res["GPU_COMPOSITION_FREE"]["eval_warp_py_modifierad"]
    ) else "FAIL"

    os.makedirs(os.path.dirname(OUTP), exist_ok=True)
    with open(OUTP, "w", encoding="utf-8") as f:
        json.dump(res, f, indent=1, ensure_ascii=False)
    log(f"WROTE {OUTP} VERDICT={res['VERDICT']}")
    return 0 if res["VERDICT"] == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
